# Generated by Django 4.0.1 on 2022-01-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcuser',
            table='fcuser',
        ),
    ]
