# Generated by Django 4.0 on 2022-03-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '계정', 'verbose_name_plural': '계정'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
